name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 300
          days-before-issue-close: 65
          stale-issue-label: "stale"
          stale-issue-message: "We consider issues as stale if there has been no activity in them for 10 months."
          close-issue-message: "This issue was closed after 1 year of inactivity."
          exempt-issue-labels: "bug,enhancement"
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
